name: crud_user
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'


dependencies:
  path: ^1.8.0
  sembast: ^3.1.1 
  get_server: ^1.1.1

dev_dependencies:
  lints: ^1.0.0
