// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCneij9CcT-1q2vfvselKG-2xNq4xxq9XY',
    appId: '1:925549519071:web:ee7bfc37a0fb1402d4896a',
    messagingSenderId: '925549519071',
    projectId: 'flutter-push-aula',
    authDomain: 'flutter-push-aula.firebaseapp.com',
    storageBucket: 'flutter-push-aula.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7HsD5NwBvivTHxnt1QW8qD6HxsHzm-UY',
    appId: '1:925549519071:android:d1a7f1f0af726252d4896a',
    messagingSenderId: '925549519071',
    projectId: 'flutter-push-aula',
    storageBucket: 'flutter-push-aula.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfv7dYEX1v84ytZL6JvwGaWZXCjrGNUJA',
    appId: '1:925549519071:ios:5284144a81217f8dd4896a',
    messagingSenderId: '925549519071',
    projectId: 'flutter-push-aula',
    storageBucket: 'flutter-push-aula.appspot.com',
    iosClientId: '925549519071-lk5423gsbhim7kndvvloohges2m8i259.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPushAula',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfv7dYEX1v84ytZL6JvwGaWZXCjrGNUJA',
    appId: '1:925549519071:ios:5284144a81217f8dd4896a',
    messagingSenderId: '925549519071',
    projectId: 'flutter-push-aula',
    storageBucket: 'flutter-push-aula.appspot.com',
    iosClientId: '925549519071-lk5423gsbhim7kndvvloohges2m8i259.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPushAula',
  );
}
